# diccid/.circleci/config.yml
---
version: 2.1
orbs:
  skip-wip-ci: artsy/skip-wip-ci@0.3.0

jobs:
  build:
    docker:
      - image: sprax/diccid-kid-a:0.0.6

    steps:
      - check-skippable-pr
      - run:
          name: setup
          command: |
            echo "In setup..."
            ls -lahFG

      - checkout

      - run:
          name: build and test
          command: |
            echo "In build and test..."
            cd src && g++ -std=c++11  main.cpp -o main && ./main
            cd ..
            ./setup.sh
